---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
## 網站資料爬取
```{r}
library(xml2)
library(rvest) ##第一次使用要先安裝 install.packages("rvest")
##read_html
##html_nodes
##html_text
allframe = data.frame(Title=character(),
                      Author=character(),
                      PushNum=character())
for(i in 4637:4642){
PTTURL<-paste0("https://www.ptt.cc/bbs/NBA/index",i,".html") 
PTTContent <- read_html(PTTURL)
post_title <- PTTContent %>% html_nodes(".title") %>% html_text() 
post_title <- gsub("\n",replacement="",post_title)
post_title <- gsub("\t",replacement="",post_title)
post_author<- PTTContent %>% html_nodes(".author") %>% html_text()
post_pushnum <- PTTContent %>% html_nodes(".nrec") %>% html_text()
PTTframe <- data.frame(Title = post_title, Author = post_author, PushNum = post_pushnum)
allframe <- rbind(allframe,PTTframe)
}
```

## 爬蟲結果呈現
```{r}
knitr::kable(allframe) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
str(allframe)
table(allframe$Author)
```

共爬出120篇文章標題。
adam7148, checktime,bigDwinsch 文章數最多,每人各發表3篇文章。


```{r}
table(allframe$Author)
table(allframe$PushNum)
```

Author為-表示文章已被刪除，共有4篇文章被刪除。
爬蟲資料中，推文數超過一定數值會顯示為"爆"。
推文數PushNum並不全為數字，有些文章的推文數為"爆"、"X1"、"X2"、"X3"。

